name: 'deploy heroku'
on: 
  push: 
      branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        usesL: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
      - name: Go Test
        run: go test ./...
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}